function drivedata = importDriveData(filename, num)
%IMPORTFILE Import data from a text file
%  DRIVEDATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  DRIVEDATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  drivedata = importfile("C:\Users\zuhai\Documents\Report Work\drivedata.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Mar-2024 22:19:13

%% Input handling

% If dataLines is not specified, define defaults
dataLines = [1, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", num);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
for idx = 1:num
    opts.VariableNames{idx} = char(strcat("VarName",num2str(idx)));
    opts.VariableTypes{idx} = 'double';
end

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
drivedata = readtable(filename, opts);

end